version: "3.3"
services:
 front:
  build: .
  depends_on:
  - "db"
  - "back"
  db:
   image: redis
  back:
   build: .
   image: back:latest
   depends_on:
   - “db”
   command: |
 ["./wait-for-it.sh", "db:5432"]
# proxy:
#  image: nginx
# From registry
#back: ODS
#  build: ./back
#  image: back:latest